'use strict';
window.VisualStory = (() => {
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={split:'Tách thành phần',categories:'Phân loại',sequence:'Từng bước',cycle:'Chu trình',compare:'Đối chiếu',verify:'Kiểm chứng'};
 let timer=null;
 function stop(){clearInterval(timer);timer=null;}
 function draw(v,id){return `<section class="visual-story" id="visual-${id}" data-visual="${esc(JSON.stringify(v))}" data-step="-1"><header><span>${names[v.type]}</span><small>Ảnh phác có cấu trúc · Không phải video</small></header><div class="visual-grid visual-${v.type}">${v.nodes.map((n,i)=>`<article class="visual-item" data-node="${esc(n.id)}"><b class="visual-number">${String(i+1).padStart(2,'0')}</b><h3>${esc(n.label)}</h3><p>${esc(n.detail)}</p></article>`).join('')}</div><div class="visual-relations">${v.edges.map(e=>`<div data-edge="${esc(e.from)},${esc(e.to)}"><span>${esc(v.nodes.find(n=>n.id===e.from)?.label)}</span><b>${v.type==='compare'?'≠':v.type==='categories'||v.type==='split'?'·':'→'} ${esc(e.label)}</b><span>${esc(v.nodes.find(n=>n.id===e.to)?.label)}</span></div>`).join('')}</div>${v.type==='cycle'?'<div class="loop-note">↻ Tiếp tục lặp lại chu trình</div>':''}${v.example_note?`<aside class="visual-example">Ví dụ minh họa: ${esc(v.example_note)}</aside>`:''}<p class="visual-caption" aria-live="polite">Xem toàn bộ · Bấm Xem diễn tiến để hiểu từng bước.</p><div class="visual-controls">${[['play','Xem diễn tiến'],['pause','Dừng'],['prev','Trước'],['next','Sau'],['all','Xem toàn bộ']].map(([a,t])=>`<button type="button" id="visual-${id}-${a}" class="btn ${a==='play'?'primary':''}" data-v-action="${a}">${t}</button>`).join('')}</div></section>`;}
 function step(root,n){const v=JSON.parse(root.dataset.visual);n=Math.max(-1,Math.min(v.steps.length-1,n));root.dataset.step=n;const ids=n<0?v.nodes.map(x=>x.id):v.steps[n].visible_ids;root.querySelectorAll('[data-node]').forEach(el=>el.classList.toggle('visual-muted',!ids.includes(el.dataset.node)));root.querySelectorAll('[data-edge]').forEach(el=>el.hidden=!el.dataset.edge.split(',').every(id=>ids.includes(id)));root.querySelector('.visual-caption').textContent=n<0?'Xem toàn bộ':`${n+1}/${v.steps.length} · ${v.steps[n].caption}`;root.querySelector('[data-v-action="prev"]').disabled=n<=0;root.querySelector('[data-v-action="next"]').disabled=n===v.steps.length-1;}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-v-action]');if(!b)return;const root=b.closest('.visual-story'),v=JSON.parse(root.dataset.visual),a=b.dataset.vAction;stop();if(a==='pause')return;if(a==='all')return step(root,-1);if(a==='prev'||a==='next')return step(root,Number(root.dataset.step)+(a==='next'?1:-1));step(root,0);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;timer=setInterval(()=>{if(!root.isConnected){stop();return;}const n=Number(root.dataset.step)+1;if(n>=v.steps.length){stop();return;}step(root,n);},2600);});
 new MutationObserver(()=>{if(!document.querySelector('.visual-story'))stop();}).observe(document.body,{childList:true,subtree:true});
 return {draw,stop};
})();
